### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by neuromancer** [chkuendig/scummvm-demo#1]
Hi!

I'm following your neat emscripten port of scummvm and I was wondering if you plan to keep it updated with the latest release and more demos.

Thanks!

**Comment by chkuendig** [comment]
Hi,

yes, I'm planning to keep it updated. 

Prio #1 right now is to make it possible to build a version with all engines enabled so I can provide a version with all demos enabled. At the  moment the binary with all engines enabled would be way too big (>100MB), and dynamic plugins dont work well with Asyncify and pthreads. 

Prio #2 is to improve the filesystem handling so we can eventually sync saves and games with cloud storage like in the native client. (Emscripten is currently redoing most of the FS layer, so I'm holding off with that for now)

**Comment by chkuendig** [comment]
Closing this. I added some more details at https://github.com/chkuendig/scummvm/blob/emscripten/dists/emscripten/README.md
