### ISSUE TITLE
Broken deployment if the filesystem is not located in the web root

### ISSUE THREAD

**Issue by neuromancer** [chkuendig/scummvm-demo#11]
My current deployment works fine locally, but fails when using the github pages: https://neuromancer.github.io/scummvm-demo/

I believe this is caused because the deployment is performed in `scummvm-demo` but the filesystem code will try to download the `index.json` files from the root, instead of using the prefix.

**Comment by neuromancer** [comment]
Was this fixed? (I changed my deployment to use the root directory and I haven't retested since that)

**Comment by chkuendig** [comment]
This is fixed.
