### ISSUE TITLE
Update demo page

### ISSUE THREAD

**Issue by markusbkk** [chkuendig/scummvm-demo#19]
Hey there.

Any chance you could update the demo site with your most recent code changes?
Would love to see if they improved performance.

I'm in bed with a broken back RN and can't get it to run locally (nodeJS is seriously detrimental to my physical and mental health. Dunno why Puppeteer no longer works and other packages take forever).

**Comment by chkuendig** [comment]
I updated the demo page as part of a larger PR I submitted today. Hopefully that helps :)

**Comment by markusbkk** [comment]
> I updated the demo page as part of a larger PR I submitted today. Hopefully that helps :)

Thanks so much! I'm extremely happy with the performance of the Grim Fandango demo. There's only minimal stuttering now.
