### ISSUE TITLE
Feature request: pull icons from https://github.com/scummvm/scummvm-icons

### ISSUE THREAD

**Issue by neuromancer** [chkuendig/scummvm-demo#6]
I believe the icons file is not updated, unless you manually pull and compile it from [the corresponding repository](https://github.com/scummvm/scummvm-icons). Perhaps could be nice to frequently pull and get the latest ones in the demo.

**Comment by chkuendig** [comment]
This is a great idea. Either by packing a full set of icons (might not cause any issues now that we can read data as range requests) or by changing the backend on the C++ side to download these directly.

I'll leave this open so I won't forget about it.
